apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: category
  name: category
  namespace: aditya
spec:
  replicas: 3
  selector:
    matchLabels:
      app: category
  strategy: {}
  template:
    metadata:
      labels:
        app: category
    spec:
      volumes:
      - name: log-volume
        emptyDir: {}
      containers:
      - image: adityapratapbhuyan/kube-ms-workshop:category-v1
        name: category
        env:
        - name: spring.jpa.hibernate.ddl-auto
          value: "update"
        - name: management.endpoint.health.show-details
          value: "always"
        - name: management.endpoints.web.exposure.include
          value: "*"
        - name: logging.file.name
          value: "/var/tmp/category.log"
        ports:
        - containerPort: 8082
        volumeMounts:
        - name: log-volume
          mountPath: "/var/tmp/"
        resources: {}
status: {}
