apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  namespace: aditya
  labels:
    type: local
spec:
  storageClassName: aditya-mysql
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim
  namespace: aditya
spec:
  storageClassName: aditya-mysql
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi